name: CI

on:
  push:
  pull_request:

jobs:
  melpa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run MELPA-style checks
        uses: leotaku/elisp-check@master
        with:
          check: melpa
          file: "arrow.el"
          warnings_as_errors: true
